SENDGRID_USERNAME: app37653191@heroku.com
SENDGRID_PASSWORD: yar6xuewUnDmuY6m
AWS_ACCESS_KEY_ID: AKIAIDULIC55IHWCBLUQ
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: bloccit-rails-development2323
production:
  AWS_BUCKET: bloccit-rails-production2323




